import type {Metadata} from "next";
import React, {Suspense} from "react";
import {checkAuthenticationAndMembership, getQueryPets} from "@/lib/server-utils";
import SearchForm from "@/components/search-form";
import TablePagination from "@/components/table-pagination";
import PetButton from "@/components/pet-button";
import PetsTable from "@/components/pets-table";
import PetContextProvider from "@/contexts/pet-context-provider";
import {prisma} from "@/lib/prisma";
import EntriesPerPage from "@/components/entries-per-page";
import {parseSearchParams} from "@/lib/utils";

type PageProps = {
    searchParams: Promise<{
        search?: string;
        page?: string;
    }>
}

export const metadata: Metadata = {
    title: "All Pets - Pawramid",
    description: "Generated by create next app",
};

export default async function Page({searchParams}: PageProps) {
    const user = await checkAuthenticationAndMembership();

    const searchParamsResults = await searchParams;
    const {search, page, entries} = await parseSearchParams(searchParamsResults);

    const {pets, totalPages, totalPets, currentPage} = await getQueryPets({
        search,
        page,
        entries
    });

    const clients = await prisma.client.findMany({
        where: {
            userId: user.id
        }
    })

    return (
        <PetContextProvider data={pets} clientsData={clients}>
            <div className="flex flex-1 flex-col gap-4 p-4">
                <div className="grid auto-rows-min gap-4 md:grid-cols-2">
                    <div className="flex items-center">
                        <p className="text-xl font-semibold">All Pets</p>
                    </div>
                    <div className="flex justify-end space-x-3">
                        <SearchForm pageName="pets" initialSearch={search}/>
                        <PetButton actionType="add">Add New Pet</PetButton>
                    </div>
                </div>
                <Suspense fallback={<div>Loading pets...</div>}>
                    <PetsTable/>
                </Suspense>
                <div className="flex justify-between space-x-3">
                    <div>
                        <EntriesPerPage pageName="pets" entries={entries} totalItems={totalPets}
                                        searchParamsResults={searchParamsResults}/></div>
                    <div>
                        <TablePagination pageName="pets" currentPage={currentPage!}
                                         totalPages={totalPages!}
                                         searchParamsResults={searchParamsResults}/>
                    </div>
                </div>
            </div>
        </PetContextProvider>
    )
}