import type {Metadata} from "next";
import {Inter} from 'next/font/google'
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/contexts/theme-provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: "Pawramid",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${inter.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
